services:
  - type: web
    name: talk2dhand
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
    buildFilter:
      paths:
        - app.py
        - templates/**
        - static/**
        - "hand sign model cnn tensorflow/hand_landmarks.h5" 